package net.justmachinery.shade.tests

import kotlinx.html.HtmlBlockTag
import kotlinx.html.p
import net.justmachinery.shade.component.Component
import net.justmachinery.shade.generated.routing.ShopSpecRouter
import net.justmachinery.shade.generated.routing.build
import net.justmachinery.shade.routing.annotation.QueryParamSpec
import net.justmachinery.shade.routing.annotation.RoutingSpecBase
import net.justmachinery.shade.routing.annotation.processor.GenerateRouting
import net.justmachinery.shade.routing.base.InternalUrlInfo
import net.justmachinery.shade.routing.base.UrlInfo
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

@GenerateRouting
object ShopSpec : RoutingSpecBase() {
    override fun internalTransform(urlInfo : InternalUrlInfo) = urlInfo.addPathPrefix("/shop")

    val index = indexPage()
    val item = page("item", ItemParams)
    val notFound = notFound()
}

object ItemParams : QueryParamSpec {
    val id = intParam("id")
}

private class ShopPage : Component<UrlInfo>() {
    override fun HtmlBlockTag.render() {
        startDispatching(props, { it.removePathPrefix("/shop") }, object : ShopSpecRouter<HtmlBlockTag>(ShopSpec) {
            override fun HtmlBlockTag.index() {
                p { +"shop index" }
            }

            override fun HtmlBlockTag.item(params : ItemParams) {
                p { +"item ${params.id}" }
            }

            override fun HtmlBlockTag.notFound() {
                p { +"no such page" }
            }
        })
    }
}

/**
 * The routers here are generated by the KSP processor from [ShopSpec].
 */
class AnnotationRoutingTest {
    private fun render(url : String) : ShadeTest {
        val path = url.substringBefore("?")
        val query = url.substringAfter("?", "")
        return ShadeTest().render { it.add(ShopPage::class, UrlInfo.of(path, query)) }
    }

    @Test
    fun `the index page is dispatched for the spec's root`() {
        render("/shop").assertShows("shop index")
    }

    @Test
    fun `a page's query params are parsed and passed to it`() {
        render("/shop/item?id=42").assertShows("item 42")
    }

    @Test
    fun `a built route round trips back to the page that built it`() {
        val route = ShopSpec.build().item(id = 7).asExternalUrl()

        assertEquals("/shop/item?id=7", route)
        render(route).assertShows("item 7")
    }

    @Test
    fun `a page whose params do not parse is not matched`() {
        render("/shop/item?id=notanumber").assertShows("no such page")
    }

    @Test
    fun `an unknown path falls to notFound`() {
        render("/shop/nothing").assertShows("no such page")
    }
}
